// Auto-generated by napi-rs at build time.
// This placeholder allows the package to be imported before building.
export function computeSimilarity(_componentsJson) {
	throw new Error(
		"@doppel-ts/native has not been built. Run `pnpm build` in packages/native first.",
	);
}
